### ISSUE TITLE
0.2.39 applications not upgrading and subsequently breaking

### ISSUE THREAD

**Issue by sudo-a9** [mynodebtc/mynode#559]
**Describe the bug**
After upgrading to from 0.2.38 to 0.2.39 some of my apps did not upgrade.  When I click upgrade, it does not work.  When I reinstall, the apps break, and that is where I am stuck.  The apps that have had issues are: Pool, Thunderhub, Specter, and Whirlpool.

**Expected behavior**
All installed and enabled apps normally upgrade seamlessly.  Just to be clear, some apps (e.g. MemPool and LND) did upgrade normally.

**MyNode hardware (please complete the following information):**
 - Device: [e.g.Raspi4]
 - Version 0.2.39

I have attempted to reinstall the upgrade, that did not work.  

EDIT:

Here is the log from Specter.

-- Logs begin at Mon 2021-08-16 21:45:41 CDT, end at Mon 2021-08-16 22:06:31 CDT. --
Aug 16 22:06:09 myNode systemd[1]: Failed to start Specter.
Aug 16 22:06:09 myNode systemd[1]: specter.service: Failed with result 'exit-code'.
Aug 16 22:06:09 myNode systemd[1]: specter.service: Control process exited, code=exited, status=200/CHDIR
Aug 16 22:06:09 myNode systemd[17434]: specter.service: Failed at step CHDIR spawning /usr/bin/is_not_shutting_down.sh: No such file or directory
Aug 16 22:06:09 myNode systemd[17434]: specter.service: Changing to the requested working directory failed: No such file or directory
Aug 16 22:06:09 myNode systemd[1]: Starting Specter...

Here is the log from Thunderhub.

-- Logs begin at Mon 2021-08-16 22:10:05 CDT, end at Mon 2021-08-16 23:10:01 CDT. --
Aug 16 23:09:33 myNode systemd[1]: Failed to start Thunderhub.
Aug 16 23:09:33 myNode systemd[1]: thunderhub.service: Failed with result 'exit-code'.
Aug 16 23:09:33 myNode systemd[1]: thunderhub.service: Control process exited, code=exited, status=200/CHDIR
Aug 16 23:09:33 myNode systemd[12560]: thunderhub.service: Failed at step CHDIR spawning /usr/bin/is_not_shutting_down.sh: No such file or directory
Aug 16 23:09:33 myNode systemd[12560]: thunderhub.service: Changing to the requested working directory failed: No such file or directory
Aug 16 23:09:33 myNode systemd[1]: Starting Thunderhub...

**Comment by tehelsper** [comment]
Can you try upgrading to v0.2.40 and see how it goes?

**Comment by imacfan** [comment]
> Can you try upgrading to v0.2.40 and see how it goes?

some issue with Dojo.. it won't upgrade on v0.2.40

**Comment by sudo-a9** [comment]
> 
> 
> Can you try upgrading to v0.2.40 and see how it goes?

Fixed!  Thunderhub is green (enabled) but giving me an "Internal Server Error" when I try to access its WebGUI though.

**Comment by AngelicInsight** [comment]
My experience is the same after upgrade to v0.2.40. Thunderhub is green but displays "Internal Server Error"  when accessing its WebGUI. 

-- Logs begin at Tue 2021-08-17 20:44:52 CDT, end at Tue 2021-08-17 21:06:28 CDT. --
Aug 17 20:53:04 myNode thunderhub[3400]:     at createApolloClient (/opt/mynode/thunderhub/.next/server/chunks/2839.js:70:11)
Aug 17 20:53:04 myNode thunderhub[3400]:     at createIsomorphLink (/opt/mynode/thunderhub/.next/server/chunks/2839.js:57:9)
Aug 17 20:53:04 myNode thunderhub[3400]:     at __webpack_require__ (/opt/mynode/thunderhub/.next/server/webpack-runtime.js:25:42)
Aug 17 20:53:04 myNode thunderhub[3400]:     at Object.7822 (/opt/mynode/thunderhub/.next/server/chunks/9107.js:778:104)
Aug 17 20:53:04 myNode thunderhub[3400]:     at getAccounts (/opt/mynode/thunderhub/.next/server/chunks/9107.js:480:10)
Aug 17 20:53:04 myNode thunderhub[3400]:     at getAccountsFromYaml (/opt/mynode/thunderhub/.next/server/chunks/9107.js:569:35)
Aug 17 20:53:04 myNode thunderhub[3400]:     at Array.map ()
Aug 17 20:53:04 myNode thunderhub[3400]:     at accounts.map (/opt/mynode/thunderhub/.next/server/chunks/9107.js:569:59)
Aug 17 20:53:04 myNode thunderhub[3400]:     at getParsedAccount (/opt/mynode/thunderhub/.next/server/chunks/9107.js:483:27)
Aug 17 20:53:04 myNode thunderhub[3400]:     at resolveEnvVarsInAccount (/opt/mynode/thunderhub/.next/server/chunks/9107.js:289:27)
Aug 17 20:53:04 myNode thunderhub[3400]: TypeError: Object.fromEntries is not a function
Aug 17 20:53:04 myNode thunderhub[3400]:     at createApolloClient (/opt/mynode/thunderhub/.next/server/chunks/2839.js:70:11)
Aug 17 20:53:04 myNode thunderhub[3400]:     at createIsomorphLink (/opt/mynode/thunderhub/.next/server/chunks/2839.js:57:9)
Aug 17 20:53:04 myNode thunderhub[3400]:     at __webpack_require__ (/opt/mynode/thunderhub/.next/server/webpack-runtime.js:25:42)
Aug 17 20:53:04 myNode thunderhub[3400]:     at Object.7822 (/opt/mynode/thunderhub/.next/server/chunks/9107.js:778:104)
Aug 17 20:53:04 myNode thunderhub[3400]:     at getAccounts (/opt/mynode/thunderhub/.next/server/chunks/9107.js:480:10)
Aug 17 20:53:04 myNode thunderhub[3400]:     at getAccountsFromYaml (/opt/mynode/thunderhub/.next/server/chunks/9107.js:569:35)
Aug 17 20:53:04 myNode thunderhub[3400]:     at Array.map ()
Aug 17 20:53:04 myNode thunderhub[3400]:     at accounts.map (/opt/mynode/thunderhub/.next/server/chunks/9107.js:569:59)
Aug 17 20:53:04 myNode thunderhub[3400]:     at getParsedAccount (/opt/mynode/thunderhub/.next/server/chunks/9107.js:483:27)
Aug 17 20:53:04 myNode thunderhub[3400]:     at resolveEnvVarsInAccount (/opt/mynode/thunderhub/.next/server/chunks/9107.js:289:27)
Aug 17 20:53:04 myNode thunderhub[3400]: TypeError: Object.fromEntries is not a function
Aug 17 20:53:04 myNode thunderhub[3400]: 2021-08-17 20:53:04 error [THUB]: No admin.macaroon file found at path: '/home/bitcoin/.lnd/data/chain/bitcoin/mainnet/'/admin.macaroon
Aug 17 20:53:04 myNode thunderhub[3400]: 2021-08-17 20:53:04 error [THUB]: No admin.macaroon file found at path: '/home/bitcoin/.lnd/data/chain/bitcoin/mainnet/'/admin.macaroon
Aug 17 20:52:48 myNode thunderhub[3400]:     at createApolloClient (/opt/mynode/thunderhub/.next/server/chunks/2839.js:70:11)
Aug 17 20:52:48 myNode thunderhub[3400]:     at createIsomorphLink (/opt/mynode/thunderhub/.next/server/chunks/2839.js:57:9)
Aug 17 20:52:48 myNode thunderhub[3400]:     at __webpack_require__ (/opt/mynode/thunderhub/.next/server/webpack-runtime.js:25:42)
Aug 17 20:52:48 myNode thunderhub[3400]:     at Object.7822 (/opt/mynode/thunderhub/.next/server/chunks/9107.js:778:104)
Aug 17 20:52:48 myNode thunderhub[3400]:     at getAccounts (/opt/mynode/thunderhub/.next/server/chunks/9107.js:480:10)
Aug 17 20:52:48 myNode thunderhub[3400]:     at getAccountsFromYaml (/opt/mynode/thunderhub/.next/server/chunks/9107.js:569:35)
Aug 17 20:52:48 myNode thunderhub[3400]:     at Array.map ()
Aug 17 20:52:48 myNode thunderhub[3400]:     at accounts.map (/opt/mynode/thunderhub/.next/server/chunks/9107.js:569:59)
Aug 17 20:52:48 myNode thunderhub[3400]:     at getParsedAccount (/opt/mynode/thunderhub/.next/server/chunks/9107.js:483:27)
Aug 17 20:52:48 myNode thunderhub[3400]:     at resolveEnvVarsInAccount (/opt/mynode/thunderhub/.next/server/chunks/9107.js:289:27)
Aug 17 20:52:48 myNode thunderhub[3400]: TypeError: Object.fromEntries is not a function
Aug 17 20:52:48 myNode thunderhub[3400]:     at createApolloClient (/opt/mynode/thunderhub/.next/server/chunks/2839.js:70:11)
Aug 17 20:52:48 myNode thunderhub[3400]:     at createIsomorphLink (/opt/mynode/thunderhub/.next/server/chunks/2839.js:57:9)
Aug 17 20:52:48 myNode thunderhub[3400]:     at __webpack_require__ (/opt/mynode/thunderhub/.next/server/webpack-runtime.js:25:42)
Aug 17 20:52:48 myNode thunderhub[3400]:     at Object.7822 (/opt/mynode/thunderhub/.next/server/chunks/9107.js:778:104)
Aug 17 20:52:48 myNode thunderhub[3400]:     at getAccounts (/opt/mynode/thunderhub/.next/server/chunks/9107.js:480:10)
Aug 17 20:52:48 myNode thunderhub[3400]:     at getAccountsFromYaml (/opt/mynode/thunderhub/.next/server/chunks/9107.js:569:35)
Aug 17 20:52:48 myNode thunderhub[3400]:     at Array.map ()
Aug 17 20:52:48 myNode thunderhub[3400]:     at accounts.map (/opt/mynode/thunderhub/.next/server/chunks/9107.js:569:59)
Aug 17 20:52:48 myNode thunderhub[3400]:     at getParsedAccount (/opt/mynode/thunderhub/.next/server/chunks/9107.js:483:27)
Aug 17 20:52:48 myNode thunderhub[3400]:     at resolveEnvVarsInAccount (/opt/mynode/thunderhub/.next/server/chunks/9107.js:289:27)
Aug 17 20:52:48 myNode thunderhub[3400]: TypeError: Object.fromEntries is not a function
Aug 17 20:52:48 myNode thunderhub[3400]: 2021-08-17 20:52:48 error [THUB]: No admin.macaroon file found at path: '/home/bitcoin/.lnd/data/chain/bitcoin/mainnet/'/admin.macaroon
Aug 17 20:52:48 myNode thunderhub[3400]: 2021-08-17 20:52:48 error [THUB]: No admin.macaroon file found at path: '/home/bitcoin/.lnd/data/chain/bitcoin/mainnet/'/admin.macaroon
Aug 17 20:52:48 myNode thunderhub[3400]:     at createApolloClient (/opt/mynode/thunderhub/.next/server/chunks/2839.js:70:11)
Aug 17 20:52:48 myNode thunderhub[3400]:     at createIsomorphLink (/opt/mynode/thunderhub/.next/server/chunks/2839.js:57:9)
Aug 17 20:52:48 myNode thunderhub[3400]:     at __webpack_require__ (/opt/mynode/thunderhub/.next/server/webpack-runtime.js:25:42)
Aug 17 20:52:48 myNode thunderhub[3400]:     at Object.7822 (/opt/mynode/thunderhub/.next/server/chunks/9107.js:778:104)
Aug 17 20:52:48 myNode thunderhub[3400]:     at getAccounts (/opt/mynode/thunderhub/.next/server/chunks/9107.js:480:10)
Aug 17 20:52:48 myNode thunderhub[3400]:     at getAccountsFromYaml (/opt/mynode/thunderhub/.next/server/chunks/9107.js:569:35)
Aug 17 20:52:48 myNode thunderhub[3400]:     at Array.map ()
Aug 17 20:52:48 myNode thunderhub[3400]:     at accounts.map (/opt/mynode/thunderhub/.next/server/chunks/9107.js:569:59)
Aug 17 20:52:48 myNode thunderhub[3400]:     at getParsedAccount (/opt/mynode/thunderhub/.next/server/chunks/9107.js:483:27)
Aug 17 20:52:48 myNode thunderhub[3400]:     at resolveEnvVarsInAccount (/opt/mynode/thunderhub/.next/server/chunks/9107.js:289:27)
Aug 17 20:52:48 myNode thunderhub[3400]: TypeError: Object.fromEntries is not a function
Aug 17 20:52:48 myNode thunderhub[3400]: 2021-08-17 20:52:48 error [THUB]: No admin.macaroon file found at path: '/home/bitcoin/.lnd/data/chain/bitcoin/mainnet/'/admin.macaroon
Aug 17 20:52:47 myNode thunderhub[3400]: 2021-08-17 20:52:47 verbose [THUB]: Found cookie at path /opt/mynode/thunderhub/.cookie
Aug 17 20:46:49 myNode thunderhub[3400]: info  - Loaded env from /opt/mynode/thunderhub/.env
Aug 17 20:46:49 myNode thunderhub[3400]: info  - Loaded env from /opt/mynode/thunderhub/.env.local
Aug 17 20:46:49 myNode thunderhub[3400]: ready - started server on 0.0.0.0:3030, url: http://localhost:3030
Aug 17 20:46:48 myNode thunderhub[3400]: > next start "-p" "3030"
Aug 17 20:46:48 myNode thunderhub[3400]: > thunderhub@0.12.24 start /opt/mynode/thunderhub
Aug 17 20:46:45 myNode systemd[1]: Started Thunderhub.
Aug 17 20:46:45 myNode thunderhub[3188]: [lncli] rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"
Aug 17 20:46:43 myNode thunderhub[3188]: Checking if LND is synced...
Aug 17 20:46:43 myNode thunderhub[3176]: Not shutting down!
Aug 17 20:46:43 myNode thunderhub[3176]: Checking if device is shutting down...
Aug 17 20:46:43 myNode systemd[1]: Starting Thunderhub...

**Comment by tehelsper** [comment]
Sorry, can you try the latest beta? It downgrades Thunderhub back to the previous release. The latest version requires a newer version of node which has not been included in a release yet.

**Comment by AngelicInsight** [comment]
I've installed beta_08-17-21_1629258990 and Thunderhub appears to have returned to normal.

**Comment by imacfan** [comment]
> I've installed beta_08-17-21_1629258990 and Thunderhub appears to have returned to normal. 

From where did you install beta. I tried via settings UI.. it didn't install beta for me

**Comment by AngelicInsight** [comment]
The settings UI worked for me. I just pressed the "Check for Updates" button and installed the beta from there.
